#161 update Setup and Configuration
WomenWhoCode/WWCodeMobile pull request #162
Opened 2024-02-04 15:18 UTC by devanshimodha

Added useful links for the setup:

- Xcode documentation
- Xcode Source Control Management
- Combining code changes in a source control repository

2024-02-05 00:03 UTC, ceceliacreates requested changes
Just a small change, it looks like the formatting for the markdown link had some extra characters.

2024-02-05 00:03 UTC, ceceliacreates commented on coding-projects/ios/README.md
> +    [Xcode Source Control Management]([https:/](https://developer.apple.com/documentation/xcode/source-control-management)/)
```suggestion
    [Xcode Source Control Management](https://developer.apple.com/documentation/xcode/source-control-management)/)
```

2024-02-11 17:38 UTC, devanshimodha commented on coding-projects/ios/README.md
> +    [Xcode Source Control Management]([https:/](https://developer.apple.com/documentation/xcode/source-control-management)/)
Fixed spacing @ceceliacreates

2024-02-14 15:12 UTC, ceceliacreates approved these changes

2024-02-14 15:13 UTC, merged

2024-02-14 15:13 UTC, ceceliacreates commented
I am going to go ahead and merge, as this is a documentation change. Looks good @devanshimodha thanks for the fix