[docs]: add usage section in README
WomenWhoCode/WWCodeMobile pull request #178
Opened 2024-02-05 03:51 UTC by CBID2

## TODO:
Closes #135 
## TODO: Request a maintainer to review your PR
* [Request a maintainer of your project to review your PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review)
* You may also [tag that maintainer in your PR](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#mentioning-people-and-teams)
* Example: @ABCD My PR is ready for review! (update with actual reviewer's Github handle)
* If applicable, also tag the maintainer on Slack

## TODO: Write a brief description of what your PR accomplished
This PR adds information about how users should interact with the To do list app.

## TODO: Attach screenshots of your changes
* This could be the screens from running the app in the simulator, or in the IDE UI Preview window.
* See [how to upload assets to your PR](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#uploading-assets)
* The idea is to make it as easy as possible for the PR reviewers to follow what you did

## TODO: Explain how to test your PR
* For example, what unit tests need to be run, if any? What buttons do you need to tap on which screens to test the app flow?
* The idea is to make it as easy as possible for the PR reviewers to follow what you did

2024-02-06 17:43 UTC, clc80 requested changes
Found a typo that could cause issues for beginners.

2024-02-06 17:43 UTC, clc80 commented on coding-projects/README.md
> +- Commit your changes: `git commit -am 'Add new feature'`.
```suggestion
- Commit your changes: `git commit -m 'Add new feature'`.
```

There shouldn't be an "a" there. I know you didn't add that there but it really should be deleted.

2024-02-06 17:45 UTC, CBID2 commented on coding-projects/README.md
> +- Commit your changes: `git commit -am 'Add new feature'`.
Hi @clc80, commit am is an actual Git command: https://git-scm.com/docs/git-am/2.33.1

2024-02-06 18:41 UTC, clc80 commented on coding-projects/README.md
> +- Commit your changes: `git commit -am 'Add new feature'`.
@CBID2 I did not know that, but that is not the intended use of it in this case. There is no patching going on. I believe they meant to use -m to commit with a message as is the most common scenario.

2024-02-06 18:44 UTC, CBID2 commented on coding-projects/README.md
> +- Commit your changes: `git commit -am 'Add new feature'`.
Hey @clc80. I realized that the article I sent you doesn't best explain this command. Here is a better one: https://teamtreehouse.com/community/git-commit-a-m-new-message-commits-all-changes-so-what-happens-when-i-just-type-git-commit-m-new-message

2024-02-06 19:10 UTC, clc80 commented on coding-projects/README.md
> +- Commit your changes: `git commit -am 'Add new feature'`.
@CBID2 The article explains that this is for two separate commands done together. `-a ` and `-m` `git commit `-a -m` not `git commit -am` as is in the PR. So can it be fixed to one or the other and not left as `am` as this is not the one we want. 

if we use `-a -m` we need to add that we are using the -a to all al files.

2024-02-06 19:14 UTC, CBID2 commented on coding-projects/README.md
> +- Commit your changes: `git commit -am 'Add new feature'`.
Ok

2024-02-09 17:55 UTC, CBID2 commented on coding-projects/README.md
> +- Commit your changes: `git commit -am 'Add new feature'`.
Hi @clc80! :) Here's an article that explains this command better than the other sources I mentioned (scroll to the end to find it): https://modulesunraveled.com/very-basics-git/performing-commits-more-quickly-m-and-options

2024-02-10 00:04 UTC, clc80 approved these changes
Thanks for your work.

2024-02-11 17:26 UTC, devanshimodha approved these changes

2024-02-11 17:27 UTC, merged