added FollowUsOnTwitterView
WomenWhoCode/WWCodeMobile pull request #184
Opened 2024-02-06 12:55 UTC by lulu-cao

Implements issue #113

@devanshimodha @clc80 My PR is ready for review!

I added a row for users to follow us on Twitter by updating SettingsView.

<img width="1394" alt="Screenshot 2024-02-06 at 8 51 36 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/90204456/ad9c8163-ee41-4526-a571-2f1a9227cb2f">

2024-02-06 14:42 UTC, devanshimodha approved these changes

2024-02-06 15:40 UTC, clc80 requested changes
Let's change the chevron to a different icon.

2024-02-06 15:40 UTC, clc80 commented on coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift
> +                Image(systemName: "chevron.right")
A chevron is usually for opening up another page, this would open up a different view. So we would need a different icon.  Something that would show that you may leave the app. 

Take a look at the different sf symbols . One example may be: 
![Screenshot 2024-02-06 at 7 39 04 AM](https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/120e732b-9e78-432a-b406-e2524fba746f)

2024-02-07 18:15 UTC, lulu-cao commented
@clc80 Just changed the icon. Thank you!

2024-02-07 18:26 UTC, merged