Issue #128: iOS - UI - Detail Screen: Scaffold initial screen with elements
WomenWhoCode/WWCodeMobile pull request #194
Opened 2024-02-08 14:12 UTC by DevHarleyA

### Changes
- Implements issue #128 - Scaffold initial screen with elements

### Screenshot

2024-02-09 23:55 UTC, clc80 requested changes
This is really good. Just one nit pick.

2024-02-09 23:55 UTC, clc80 commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
> +            Spacer()
```suggestion
            
```
Can we get rid of this spacer,  it puts too much room in the top.

2024-02-11 18:36 UTC, DevHarleyA commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
> +            Spacer()
Yes, removed!

2024-02-11 18:37 UTC, DevHarleyA commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
> +            Spacer()
I updated the screenshot as well in the description

2024-02-11 19:43 UTC, clc80 approved these changes
Thank you. Looks better.

2024-02-12 03:41 UTC, devanshimodha approved these changes

2024-02-12 03:41 UTC, merged