added update method
WomenWhoCode/WWCodeMobile pull request #207
Opened 2024-02-15 08:10 UTC by lulu-cao

@devanshimodha @clc80 My PR for issue #78 is ready for review! I added an updateTask function in DetailsViewModel and called this method when the "Done" button is clicked in DetailsView. Nothing has changed in the UI. Thank you for reviewing!  
<img width="1082" alt="Screenshot 2024-02-15 at 4 08 06 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/90204456/8e7dcb43-a57d-43e2-aeb6-07d44affea9f">

2024-02-15 17:34 UTC, clc80 requested changes
There are some extra files that were added. Can you remove those please. The .DS_Store files

Also the merge conflicts need to be addressed before we can approve and merge your project in. Let us know if you have any issues with either request.

2024-02-22 20:51 UTC, ceceliacreates commented
@lulu-cao it looks like there is still a merge conflict, can you please resolve? @clc80 @devanshimodha once that is resolved, it looks like the requested changes are ready for review.

2024-02-25 14:52 UTC, lulu-cao commented
Hello @clc80 @devanshimodha 
I've updated my pull request. Could you please take a look? Thank you.

2024-02-25 15:56 UTC, devanshimodha approved these changes

2024-02-26 00:19 UTC, clc80 approved these changes

2024-02-26 00:19 UTC, merged