Issue #212 Create Issue Tempalte To Provide Guidance on Writing Issues
WomenWhoCode/WWCodeMobile pull request #219
Opened 2024-02-19 00:05 UTC by vuinguyen

Implements issue #212 

This PR creates an issue template to help folks write better issues.

2024-02-20 00:13 UTC, clc80 commented on issue_template.md
> +## TODO: If a PR already exists, link it to this issue
```suggestion
## If a PR already exists, link it to this issue
```

Do we still need the words "TODO" on this. Seems to be already addressed in list

2024-02-20 00:14 UTC, clc80 commented on issue_template.md
> +* Do this under the Development setting gear (on the right)
maybe a screenshot of the settings gear would be better. I had no idea what the development setting gear is.

2024-02-20 00:14 UTC, clc80 requested changes
Some comments to consider.

2024-02-20 18:47 UTC, vuinguyen commented on issue_template.md
> +* Do this under the Development setting gear (on the right)
I added a link that shows how to do this instead. The link shows how to get to the development setting gear. I have no idea how to add a screenshot in markdown.

2024-02-20 18:47 UTC, vuinguyen commented on issue_template.md
> +## TODO: If a PR already exists, link it to this issue
I removed TODO: from the entire file

2024-02-20 19:01 UTC, vuinguyen commented
@clc80 I made the requested changes. Please review again when you get a chance

2024-02-20 19:33 UTC, vuinguyen commented on issue_template.md
> +* Do this under the Development setting gear (on the right)
No wait, I think I do remember how to add a screenshot in markdown. Think just need to drag it into the file. But anyway, I still think the link to the documentation is better

2024-02-22 20:47 UTC, ceceliacreates commented
HI @clc80 I reviewed and approved, can you give one final approval so we can merge? Thank you!

2024-02-23 01:59 UTC, clc80 approved these changes

2024-02-23 01:59 UTC, merged