Add Timed Activity on DetailsScreen referencing the DetailsViewModel using UserDefaults
WomenWhoCode/WWCodeMobile pull request #221
Opened 2024-02-19 20:28 UTC by SttApollo

#74 

- Implements Add Timed Activity on DetailsScreen referencing the DetailsViewModel
- I wasn't sure what kind of data persistence method we are using, so I saved it to UserDefaults forKey: activitiesKey for now 
- There are additional methods that I have implemented to test out the flow, please let me know if I should remove them for now.

2024-02-20 00:01 UTC, clc80 commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsViewModel.swift
> +        print("Activity \(name) added")
If we don't need the print for the actual UI, let's go ahead and remove it.

2024-02-20 00:02 UTC, clc80 commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsViewModel.swift
> +    func customFormattedDate(from date: Date) -> String {
love the use of your custom date formatted.

2024-02-20 00:06 UTC, clc80 commented on coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListView.swift
> +                        ForEach(viewModel.groupedActivities[date] ?? [], id: \.id) { activity in
```suggestion
                        ForEach(viewModel.groupedActivities[date] ?? [], id: \.id) { activity in
```

Is there a way to prevent the use of a nil coalescing operator here. Just seems that we shouldn't be checking for an empty array in here but should've been done before. 

I don't know if it's actually possible, but just asking.

2024-02-20 00:06 UTC, clc80 requested changes
Great job. Just a question and some minor cleanup

2024-02-21 01:39 UTC, clc80 commented
@SttApollo If you can also take care of those merge conflicts.

2024-02-22 14:48 UTC, vuinguyen commented
@clc80 I have a question, is the iOS project not using the **Task** Model class? I thought we were trying to implement persistence using SwiftData. Or are we going with user defaults for now, and completing SwiftData implementation in an integration / refactor issue later? Just trying to understand what you and @devanshimodha had in mind or what your plans were for persistence. 

Can you two provide more guidance to the contributors in the issues and in the open source channel re: plans for persistence please?

2024-02-22 20:44 UTC, ceceliacreates commented
@SttApollo what is the status of this PR? Are you able to make the requested changes so it can be closed and merged?

2024-02-22 23:21 UTC, SttApollo commented
> @SttApollo what is the status of this PR? Are you able to make the requested changes so it can be closed and merged?



> @SttApollo what is the status of this PR? Are you able to make the requested changes so it can be closed and merged?

I am able to work on this issue yes - but I would like to hear the response to vuinguyen's question so that we don't have to make more changes to the model and the data persistence I will be committing to be merged if that's ok. That will also help get a better idea how to resolve the merge conflicts.

2024-02-24 00:35 UTC, clc80 commented
> @clc80 I have a question, is the iOS project not using the **Task** Model class? I thought we were trying to implement persistence using SwiftData. Or are we going with user defaults for now, and completing SwiftData implementation in an integration / refactor issue later? Just trying to understand what you and @devanshimodha had in mind or what your plans were for persistence.
> 
> Can you two provide more guidance to the contributors in the issues and in the open source channel re: plans for persistence please?

@SttApollo We would like to incorporate swiftData if possible. Now whether you want to do so for this PR is completely up to you and how comfortable you are with it. If you prefer to push this PR as is we can do that and we can open up another issue to incorporate SwiftData. Let me know what your plans are going forward and we can make adjustments as necessary. 

This whole project is more about getting people experience with new things, working with open source and just feeling comfortable talking about projects (All things you will be doing, or are doing on the job). My whole reasoning behind doing this is to give developers a project they can have fun with and learn all while building something together and have a collaborative project that you can all put on your resume.

2024-02-24 03:22 UTC, SttApollo commented
> > @clc80 I have a question, is the iOS project not using the **Task** Model class? I thought we were trying to implement persistence using SwiftData. Or are we going with user defaults for now, and completing SwiftData implementation in an integration / refactor issue later? Just trying to understand what you and @devanshimodha had in mind or what your plans were for persistence.
> > Can you two provide more guidance to the contributors in the issues and in the open source channel re: plans for persistence please?
> 
> @SttApollo We would like to incorporate swiftData if possible. Now whether you want to do so for this PR is completely up to you and how comfortable you are with it. If you prefer to push this PR as is we can do that and we can open up another issue to incorporate SwiftData. Let me know what your plans are going forward and we can make adjustments as necessary.
> 
> This whole project is more about getting people experience with new things, working with open source and just feeling comfortable talking about projects (All things you will be doing, or are doing on the job). My whole reasoning behind doing this is to give developers a project they can have fun with and learn all while building something together and have a collaborative project that you can all put on your resume.

Yes - really appeciate the opportunity to be able to contribute to this. In that case, I will implement swiftData in this PR. Also confirming that we don't want an Activity model but rather a Task model? Thanks again!

2024-02-24 16:33 UTC, clc80 commented
@SttApollo i believe there’s already a model created. You can use that one.

2024-02-26 15:17 UTC, SttApollo commented
@clc80  @devanshimodha  - This PR is now ready for review!

2024-02-26 15:30 UTC, clc80 requested changes
Can we not add in all the .DS_Store files and there are also some files going into the android project.

2024-02-26 18:57 UTC, SttApollo commented
@clc80 woops! Sorry about that - deleted the files from my PR

2024-02-26 19:09 UTC, clc80 commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/CustomDatePickerView.swift
> +struct CustomDatePickerView: View {
Love that you put these on separate files.

2024-02-26 19:11 UTC, clc80 commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
> +    @Query var tasks: [Task]
```suggestion
    @Query var tasks: [Task]
```

I had not seen this before. 😀

2024-02-27 14:46 UTC, devanshimodha approved these changes

2024-02-27 14:46 UTC, merged