DRAFT-iOS issue 131
WomenWhoCode/WWCodeMobile pull request #223
Opened 2024-02-22 04:55 UTC by DevHarleyA

[In Progress]

### Changes
- Implements issue #131 
- Create Popup View 
- Clean up button syntax in DetailView

(Screenshot or recording)

(Request Review)

2024-02-22 17:04 UTC, clc80 commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
> +    struct PopupView: View {
Can we move this code, which is great by the way to its own file.

2024-02-22 17:05 UTC, clc80 requested changes
Just one quick change. Great job.

2024-02-23 01:57 UTC, clc80 approved these changes
Great job.

2024-02-23 09:26 UTC, devanshimodha approved these changes

2024-02-23 09:26 UTC, merged