delete timed activity
WomenWhoCode/WWCodeMobile pull request #230
Opened 2024-02-24 20:51 UTC by pelumy

## Issue Link
Implements issue #80 

## Description
This PR implements deleting timed activity logic using SwiftData.

## Video

https://github.com/WomenWhoCode/WWCodeMobile/assets/54324355/31094bb6-3cb9-43e6-b88b-15506ff84177

2024-02-24 20:52 UTC, pelumy commented
@clc80 and @devanshimodha, please this PR is ready for review

2024-02-25 00:34 UTC, clc80 commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
> +                DeleteConfirmationPopupView(showDeleteConfirmationPopup: $showDeleteConfirmationPopup, task: task!)
```suggestion
                DeleteConfirmationPopupView(showDeleteConfirmationPopup: $showDeleteConfirmationPopup, task: task!)
```

Is there a way that we can pass a task and not have to force-unwrap it. 

If there is not, can we at least use a guard and an error instead. I would hate to have our app crash without some kind of message.

2024-02-25 00:34 UTC, clc80 requested changes
Please take a look at other ways of passing task without having to forcefully unwrapping it.

2024-02-25 07:07 UTC, pelumy commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
> +                DeleteConfirmationPopupView(showDeleteConfirmationPopup: $showDeleteConfirmationPopup, task: task!)
@clc80, I don't think there is a way to pass task without it being optional. This is because while adding a new task, the task model won't be passed, and this can cause crashes in the onAppear closure of the view.

2024-02-25 07:07 UTC, pelumy commented
> Please take a look at other ways of passing task without having to forcefully unwrapping it.

@clc80, I have safely unwrapped it, thanks for pointing it out.

2024-02-26 00:16 UTC, clc80 commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
> +                if let unwrappedTask = task {
This is much better. Love it.

2024-02-26 00:16 UTC, clc80 approved these changes

2024-02-26 08:00 UTC, devanshimodha approved these changes

2024-02-26 08:00 UTC, merged