iOS Issue #240 Add Priority to Tasks
WomenWhoCode/WWCodeMobile pull request #264
Opened 2024-03-12 20:33 UTC by cyndichin

Issue #240 

## Description
* Added Priority section to the detail view for users to select priority associated with a task
* Added UI to show priority associated with a tasks
* Set default priority as medium

## Screenshots

https://github.com/WomenWhoCode/WWCodeMobile/assets/6743397/7bbe2f9f-f262-48dc-b397-43c496532e09

2024-03-12 20:33 UTC, cyndichin commented
@clc80 @devanshimodha  This PR is ready for review, thank you!

2024-03-12 20:53 UTC, clc80 requested changes
Just some small changes.

2024-03-12 20:53 UTC, clc80 commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
> +enum Priority: String, CaseIterable, Codable {
This is looking great. Can we move this enum into it's own file. The `DetailsView` is getting pretty long.

2024-03-12 20:53 UTC, clc80 commented on coding-projects/ios/TaskTracker/.DS_Store
Let's not include this

2024-03-14 14:43 UTC, cyndichin commented on coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
> +enum Priority: String, CaseIterable, Codable {
updated!

2024-03-14 14:44 UTC, cyndichin commented
@clc80 thanks for your comments, they have been addressed, requested a re-review!

2024-03-14 16:58 UTC, clc80 approved these changes
Amazing job.

2024-03-14 17:09 UTC, merged