IOS Issue #115 Add Vote Row to Settings View
WomenWhoCode/WWCodeMobile pull request #287
Opened 2024-03-26 02:21 UTC by arirays

- Closes issue #115 
- My PR is ready for review! @clc80 
- Added "Vote on future requests" Row in Settings View

<img width="253" alt="Screenshot 2024-03-25 at 4 16 10 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/51388551/33c5bab9-1e32-41e4-b7a8-52f2de3f5836">

2024-03-26 14:27 UTC, clc80 requested changes
Can we remove the 4 .DS_Store files that were added, please.

2024-03-27 22:35 UTC, arirays commented
Thank you @clc80. I've removed it but .DS_Store is still in my repo. I wonder if there's anything I'm missing?

2024-03-27 22:46 UTC, clc80 commented
> Thank you @clc80. I've removed it but .DS_Store is still in my repo. I wonder if there's anything I'm missing?

If you take care of the merge conflicts, we can just merge this in. I will fix those before we start Phase 2.

2024-03-27 23:45 UTC, clc80 approved these changes

2024-03-28 04:48 UTC, devanshimodha approved these changes

2024-03-28 04:48 UTC, merged