Add dev resources from Slack channels
WomenWhoCode/WWCodeMobile pull request #42
Opened 2023-06-25 05:59 UTC by jackiechanmakes

2023-06-27 03:31 UTC, navatijain requested changes

2023-06-27 03:31 UTC, navatijain commented on CodingResources/trans-inclusion-policies-in-the-workspace-graphic.jpg
Hey @jackiechanmakes - could you move this resource into a sub parent folder for DEI? This folder can also have the mental health and neurodiversity resources.

2023-06-27 03:31 UTC, navatijain commented on CodingResources/android-dev.md
Since we have non coding resources too, we could call it just resources - although I am open to other suggestions!

2023-06-27 03:31 UTC, navatijain commented on CodingResources/whats-new-in-xcode-15-beta.pdf
can you place this in an iOS Dev Sub folder?

2023-06-28 20:43 UTC, jackiechanmakes commented on CodingResources/trans-inclusion-policies-in-the-workspace-graphic.jpg
Done!

2023-06-28 20:44 UTC, jackiechanmakes commented on CodingResources/android-dev.md
Agree with your thoughts and done!

2023-06-28 20:44 UTC, jackiechanmakes commented on CodingResources/whats-new-in-xcode-15-beta.pdf
Done!

2023-07-29 15:17 UTC, navatijain approved these changes

2023-07-29 15:18 UTC, merged