Update README.md 1st draft
WomenWhoCode/WWCodeMobile pull request #57
Opened 2023-12-14 17:06 UTC by clc80

2023-12-14 17:18 UTC, vuinguyen commented
To implement issue #53

2023-12-16 11:48 UTC, devanshimodha approved these changes

2023-12-18 17:07 UTC, vuinguyen requested changes
This looks good! 

One suggestion:
There is a readme.template file here:
coding-projects/resources/project-readme-template.md

If you're going to create the template in this README.md file instead, I would recommend removing the project-readme-template.mid file then to avoid confusion.

Thanks for working on this issue @clc80 !

2023-12-18 17:30 UTC, vuinguyen commented on coding-projects/README.md
> +   - Submit a pull request.
I would add to this:
Short summary of contributions here:
.....

More detailed instructions for contributing and the Git workflow can be found in the Resources folder.

2023-12-19 18:30 UTC, vuinguyen approved these changes
Since Claudia is taking a break, I think the easier thing to do would be to approve and merge this PR. Then, I can submit additional changes through a separate PR.

2023-12-19 18:31 UTC, merged